### ISSUE TITLE
不能打入汉字水印？

### ISSUE THREAD

**Issue by sheiy** [zy445566/node-digital-watermarking#20]
```
BindingError {
  name: 'BindingError',
  message: 'String has UTF-16 code units that do not fit in 8 bits',
  stack: 'BindingError: String has UTF-16 code units that do not fit in 8 bits\n' +
    '    at BindingError.<anonymous> (evalmachine.<anonymous>:21:1592938)\n' +
    '    at new BindingError (eval at createNamedFunction (evalmachine.<anonymous>:21:1592644), <anonymous>:4:34)\n' +
    '    at throwBindingError (evalmachine.<anonymous>:21:1593383)\n' +
    '    at Object.toWireType (evalmachine.<anonymous>:21:1600626)\n' +
    '    at Object.putText (eval at new_ (evalmachine.<anonymous>:21:1594131), <anonymous>:8:26)\n' +
    '    at Object.putText (evalmachine.<anonymous>:21:1715548)\n' +
    '    at addTextByMat (/Volumes/data/code/cisdi/app-watermark/node_modules/digital-watermarking/lib.js:89:8)\n' +
    '    at transFormMatWithText (/Volumes/data/code/cisdi/app-watermark/node_modules/digital-watermarking/lib.js:101:5)\n' +
    '    at Object.transformImageWithText (/Volumes/data/code/cisdi/app-watermark/node_modules/digital-watermarking/lib.js:186:16)\n' +
    '    at async Function.transformImageWithText (/Volumes/data/code/cisdi/app-watermark/node_modules/digital-watermarking/index.js:33:16)'
}
```

**Comment by zy445566** [comment]
这跟汉字没关系，是因为你的字符编码是utf16，我们这个仅支持utf8
